backend:
  replicaCount: 2
  image:
    repository: ellane/k8s-labs-todo-backend
    tag: 1.0
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort:
      enabled: true
      port: 30001
  cors_allowed_origins: http://localhost:3000

database:
  host: "todo-db-service"
  name: "tododb" 
  user: "root" 
  password: "todo1234"
  rootPassword: "root1234"