apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
  labels: {{- include "todo-list-chart.labels" . | nindent 4 }}
spec:
  ports:
  - port: 3306
  selector:
    app.kubernetes.io/name: {{ include "todo-list-chart.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP